filters:
  - true

commentBody: |
  Thanks for your contribution!  Unfortunately, we don't use GitHub pull
  requests to manage code contributions to this repository as this is
  just a mirror. If you've spotted a typo, or have a content correction
  or suggestion for a new feature, please [open a new Issue.](https://github.com/XanaduAI/Xanadu-Quantum-Codebook/issues/new/choose)

addLabel: false
